[workspace]
resolver = "2"
members = [
  "app-file-manager",
  "cross-platform",
  "shell-dock",
  "shell-panel",
  "ui-lib",
]

[workspace.dependencies]
iced = "0.14"
iced_layershell = "0.14.2"
chrono = "0.4.43"
