[package]
name = "shell-dock"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { workspace = true }
iced_layershell = { workspace = true }
so-core = { path = "../so-core/" }
so-base = { path = "../so-base/" }
