[package]
name = "app-file-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { workspace = true, features = ["tokio"] }
tokio = { workspace = true, features = ["fs"] }
so-base = { path = "../so-base/" }
