[package]
name = "cross-platform"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { workspace = true, features = ["image", "web-colors", "webgl"] }
so-core = { path = "../so-core/" }
so-base = { path = "../so-base/" }
