[package]
name = "so-core"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { workspace = true, features = ["tokio", "image"] }
chrono = { workspace = true }
app-file-manager = { path = "../app-file-manager/" }
so-base = { path = "../so-base/" }
